#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import JointState

from markers import *
from proyectofunctions import *

if __name__ == '__main__':

  rospy.init_node("testForwardKinematics")
  pub = rospy.Publisher('joint_states', JointState, queue_size=1000)
  bmarker = BallMarker(color['GREEN'])

  # Joint names
  jnames = ['revo_1', 'revo_2', 'revo_3','revo_4', 'revo_5', 'revo_6']
  # Joint Configuration
  q =  [0.7, 0.5, -0.6, 0.3, 0, 0]

  # End effector with respect to the base
  T = fkine(q)
  print( np.round(T, 3) )
  bmarker.position(T)

  # Object (message) whose type is JointState
  jstate = JointState()
  # Set values to the message
  jstate.header.stamp = rospy.Time.now()
  jstate.name = jnames
  # Add the head joint value (with value 0) to the joints
  jstate.position = q

  # Loop rate (in Hz)
  rate = rospy.Rate(600)
  # Continuous execution loop
  while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    # Wait for the next iteration
    rate.sleep()
